[gameplay]
toggle_sprint = false
toggle_ads = false
toggle_crouch = false
sensitivity = 1.2000001668930054

[graphics]
resolution = [
    0,
    0,
]
texture_quality = "High"
shadow_quality = "High"
view_distance = 1000.0
fps_cap = 0
fov = 90.0

[debug]
show_fps = true
max_fps_display = 144
show_resource_usage = true
show_hitboxes = false
free_cam = false
debug_mode = false
show_vertex_count = true
show_ping = true
show_crosshair_debug = false
god_mode = false
infinite_ammo = false
show_wireframe = false
