move_forward = "KeyW"
move_backward = "KeyS"
move_left = "KeyA"
move_right = "KeyD"
jump = "Space"
sprint = "ShiftLeft"
crouch = "ControlLeft"
interact = "KeyE"
grenade = "KeyG"
melee = "KeyF"
stats = "F3"
pause = "Escape"
shoot = "Left"
ads = "Right"
reload = "KeyR"
prone = "KeyZ"
lean_left = "KeyQ"
lean_right = "KeyE"
scoreboard = "Tab"
